// allocator_vs_io_comparison_marker
// Category: hn_context
// HN marker: allocator_vs_io
// Article marker: allocator_comparison
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=allocator_vs_io_comparison_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=allocator_vs_io\n", .{});
    std.debug.print("ARTICLE_MARKER=allocator_comparison\n", .{});
    std.debug.print("ALLOCATOR_VS_IO_COMPARISON=1\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_allocator = @hasDecl(std.mem, "Allocator");
    std.debug.print("HAS_IO={} HAS_ALLOCATOR={}\n", .{has_Io, has_allocator});
}
