// allocator_vs_io_comparison_marker
// Category: hn_context
// Purpose: allocator vs IO comparison
// HN marker: allocator_vs_io
// Article marker: allocator_comparison
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: allocator_vs_io_comparison_marker
    // Purpose: allocator vs IO comparison
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=allocator_vs_io_comparison_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=allocator_vs_io\n", .{});
    std.debug.print("ARTICLE_MARKER=allocator_comparison\n", .{});
}
