// async_not_concurrency_context_marker
// Category: async_context
// Purpose: async is not concurrency
// HN marker: async_vs_concurrent
// Article marker: async_model
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: async_not_concurrency_context_marker
    // Purpose: async is not concurrency
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=async_not_concurrency_context_marker\n", .{});
    std.debug.print("CATEGORY=async_context\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=async_model\n", .{});
}
