// async_not_concurrency_context_marker
// Category: async_context
// HN marker: async_vs_concurrent
// Article marker: async_model
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=async_not_concurrency_context_marker\n", .{});
    std.debug.print("CATEGORY=async_context\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=async_model\n", .{});
    std.debug.print("ASYNC_NOT_CONCURRENCY=1\n", .{});
    if (@hasDecl(std, "Io")) {
        std.debug.print("HAS_IO=1\n", .{});
    }
}
