// async_concurrent_renamed_context_marker
// Category: async_api
// HN marker: pre_1_0_api_changed
// Article marker: api_renaming
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=async_concurrent_renamed_context_marker\n", .{});
    std.debug.print("CATEGORY=async_api\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=api_renaming\n", .{});
    const has_Io = @hasDecl(std, "Io");
    if (has_Io) {
        const has_concurrent = @hasDecl(std.Io, "concurrent");
        const has_asyncConcurrent = @hasDecl(std.Io, "asyncConcurrent");
        std.debug.print("CONCURRENT_API: concurrent={} asyncConcurrent={}\n", .{has_concurrent, has_asyncConcurrent});
        std.debug.print("API_RENAME_CONTEXT=1\n", .{});
    }
}
