// await_idempotent_context_marker
// Category: await_cancel
// HN marker: cancellation_await_ordering
// Article marker: await_ordering
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=await_idempotent_context_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=await_ordering\n", .{});
    std.debug.print("AWAIT_IDEMPOTENT_CONTEXT=check_std_Io_docs\n", .{});
    if (@hasDecl(std, "Io")) {
        std.debug.print("HAS_IO=1\n", .{});
    }
}
