// await_then_try_ordering_marker
// Category: await_cancel
// HN marker: cancellation_await_ordering
// Article marker: await_ordering
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=await_then_try_ordering_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=await_ordering\n", .{});
    std.debug.print("AWAIT_THEN_TRY_ORDERING=1\n", .{});
}
