// cancel_cleanup_context_marker
// Category: await_cancel
// HN marker: cancellation_await_ordering
// Article marker: cancel_cleanup
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=cancel_cleanup_context_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=cancel_cleanup\n", .{});
    std.debug.print("CANCEL_CLEANUP_CONTEXT=1\n", .{});
}
