// compile_error_capture_marker
// Category: compile_check
// HN marker: pre_1_0_api_changed
// Article marker: compile_validation
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=compile_error_capture_marker\n", .{});
    std.debug.print("CATEGORY=compile_check\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=compile_validation\n", .{});
    const has_Io = @hasDecl(std, "Io");
    std.debug.print("COMPILE_ERROR_CAPTURE_TEST HAS_IO={}\n", .{has_Io});
    if (!has_Io) @compileError("std.Io missing - api_changed");
}
