// compile_error_capture_marker
// Category: compile_check
// Purpose: compile error capture test
// HN marker: pre_1_0_api_changed
// Article marker: compile_validation
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: compile_error_capture_marker
    // Purpose: compile error capture test
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=compile_error_capture_marker\n", .{});
    std.debug.print("CATEGORY=compile_check\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=compile_validation\n", .{});
}
