// concurrency_unavailable_context_marker
// Category: concurrent_context
// Purpose: error.ConcurrencyUnavailable context
// HN marker: deadlock_concurrency_unavailable
// Article marker: concurrency_unavailable
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: concurrency_unavailable_context_marker
    // Purpose: error.ConcurrencyUnavailable context
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=concurrency_unavailable_context_marker\n", .{});
    std.debug.print("CATEGORY=concurrent_context\n", .{});
    std.debug.print("HN_MARKER=deadlock_concurrency_unavailable\n", .{});
    std.debug.print("ARTICLE_MARKER=concurrency_unavailable\n", .{});
}
