// concurrent_required_context_marker
// Category: concurrent_context
// Purpose: concurrent required context
// HN marker: async_vs_concurrent
// Article marker: concurrent_required
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: concurrent_required_context_marker
    // Purpose: concurrent required context
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=concurrent_required_context_marker\n", .{});
    std.debug.print("CATEGORY=concurrent_context\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=concurrent_required\n", .{});
}
