// concurrency_unavailable_context_marker
// Category: concurrent_context
// HN marker: deadlock_concurrency_unavailable
// Article marker: concurrency_unavailable
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=concurrency_unavailable_context_marker\n", .{});
    std.debug.print("CATEGORY=concurrent_context\n", .{});
    std.debug.print("HN_MARKER=deadlock_concurrency_unavailable\n", .{});
    std.debug.print("ARTICLE_MARKER=concurrency_unavailable\n", .{});
    std.debug.print("CONCURRENCY_UNAVAILABLE_CONTEXT=1\n", .{});
}
