// concurrent_required_context_marker
// Category: concurrent_context
// HN marker: async_vs_concurrent
// Article marker: concurrent_required
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=concurrent_required_context_marker\n", .{});
    std.debug.print("CATEGORY=concurrent_context\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=concurrent_required\n", .{});
    std.debug.print("CONCURRENT_REQUIRED_CONTEXT=1\n", .{});
    if (@hasDecl(std, "Io")) {
        const has_concurrent = @hasDecl(std.Io, "concurrent");
        std.debug.print("HAS_CONCURRENT={}\n", .{has_concurrent});
    }
}
