// deadlock_not_run_timeout_marker
// Category: deadlock
// HN marker: deadlock_concurrency_unavailable
// Article marker: deadlock
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=deadlock_not_run_timeout_marker\n", .{});
    std.debug.print("CATEGORY=deadlock\n", .{});
    std.debug.print("HN_MARKER=deadlock_concurrency_unavailable\n", .{});
    std.debug.print("ARTICLE_MARKER=deadlock\n", .{});
    std.debug.print("DEADLOCK_NOT_RUN=1 TIMEOUT_GUARD=1\n", .{});
}
