// debug_build_context_marker
// Category: build_mode
// HN marker: pre_1_0_api_changed
// Article marker: build_mode
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=debug_build_context_marker\n", .{});
    std.debug.print("CATEGORY=build_mode\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=build_mode\n", .{});
    const mode = @import("builtin").mode;
    std.debug.print("BUILD_MODE={}\n", .{@tagName(mode)});
}
