// defer_cancel_cleanup_marker
// Category: await_cancel
// HN marker: cancellation_await_ordering
// Article marker: cancel_cleanup
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=defer_cancel_cleanup_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=cancel_cleanup\n", .{});
    std.debug.print("DEFER_CANCEL_CLEANUP=1\n", .{});
    var cleaned: bool = false;
    defer cleaned = true;
    std.debug.print("CLEANUP_EXAMPLE=1\n", .{});
    _ = cleaned;
}
