// defer_cancel_cleanup_marker
// Category: await_cancel
// Purpose: defer cancel cleanup
// HN marker: cancellation_await_ordering
// Article marker: cancel_cleanup
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: defer_cancel_cleanup_marker
    // Purpose: defer cancel cleanup
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=defer_cancel_cleanup_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=cancel_cleanup\n", .{});
}
