// function_coloring_debate_marker
// Category: hn_context
// HN marker: function_coloring
// Article marker: function_coloring
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=function_coloring_debate_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=function_coloring\n", .{});
    std.debug.print("ARTICLE_MARKER=function_coloring\n", .{});
    std.debug.print("FUNCTION_COLORING_DEBATE=hn_45746020\n", .{});
    const has_Io = @hasDecl(std, "Io");
    std.debug.print("HAS_IO={}\n", .{has_Io});
}
