// future_await_exists_marker
// Category: await_cancel
// HN marker: cancellation_await_ordering
// Article marker: await_api
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=future_await_exists_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=await_api\n", .{});
    const has_Io = @hasDecl(std, "Io");
    if (has_Io) {
        std.debug.print("IO_HAS_AWAIT_DECL={}\n", .{@hasDecl(std.Io, "await")});
    }
}
