// future_await_exists_marker
// Category: await_cancel
// Purpose: check future.await exists
// HN marker: cancellation_await_ordering
// Article marker: await_api
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: future_await_exists_marker
    // Purpose: check future.await exists
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=future_await_exists_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=await_api\n", .{});
}
