// io_async_exists_marker
// Category: async_api
// HN marker: async_vs_concurrent
// Article marker: io_async
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_async_exists_marker\n", .{});
    std.debug.print("CATEGORY=async_api\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=io_async\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_async = has_Io and @hasDecl(std.Io, "async");
    std.debug.print("HAS_IO_ASYNC={}\n", .{has_async});
    if (has_Io) {
        const info = @typeInfo(std.Io);
        if (info == .@"struct") {
            std.debug.print("IO_DECL_COUNT={}\n", .{info.@"struct".decls.len});
        }
    }
}
