// io_concurrent_exists_marker
// Category: async_api
// HN marker: async_vs_concurrent
// Article marker: io_concurrent
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_concurrent_exists_marker\n", .{});
    std.debug.print("CATEGORY=async_api\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=io_concurrent\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_concurrent = has_Io and @hasDecl(std.Io, "concurrent");
    const has_async_concurrent = has_Io and @hasDecl(std.Io, "asyncConcurrent");
    std.debug.print("HAS_CONCURRENT={} HAS_ASYNC_CONCURRENT={}\n", .{has_concurrent, has_async_concurrent});
}
