// io_effect_token_context_marker
// Category: hn_context
// HN marker: effect_token
// Article marker: io_effect
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_effect_token_context_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=effect_token\n", .{});
    std.debug.print("ARTICLE_MARKER=io_effect\n", .{});
    std.debug.print("IO_EFFECT_TOKEN_CONTEXT=1\n", .{});
    if (@hasDecl(std, "Io")) {std.debug.print("HAS_IO=1\n", .{});}
}
