// io_effect_token_context_marker
// Category: hn_context
// Purpose: IO / effect token context
// HN marker: effect_token
// Article marker: io_effect
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: io_effect_token_context_marker
    // Purpose: IO / effect token context
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=io_effect_token_context_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=effect_token\n", .{});
    std.debug.print("ARTICLE_MARKER=io_effect\n", .{});
}
