// io_queue_put_get_context_marker
// Category: io_queue
// HN marker: standard_library_abstraction
// Article marker: io_queue
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_queue_put_get_context_marker\n", .{});
    std.debug.print("CATEGORY=io_queue\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=io_queue\n", .{});
    std.debug.print("IO_QUEUE_PUT_GET_CONTEXT=1\n", .{});
}
