// io_queue_exists_marker
// Category: io_queue
// HN marker: standard_library_abstraction
// Article marker: io_queue
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_queue_exists_marker\n", .{});
    std.debug.print("CATEGORY=io_queue\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=io_queue\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_queue = has_Io and @hasDecl(std.Io, "Queue");
    std.debug.print("HAS_IO_QUEUE={}\n", .{has_queue});
}
