// io_sleep_probe_marker
// Category: stdlib_probe
// Purpose: check io.sleep exists
// HN marker: async_vs_concurrent
// Article marker: async_model
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: io_sleep_probe_marker
    // Purpose: check io.sleep exists
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=io_sleep_probe_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=async_model\n", .{});
}
