// io_sleep_probe_marker
// Category: stdlib_probe
// HN marker: async_vs_concurrent
// Article marker: async_model
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=io_sleep_probe_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=async_model\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_sleep = has_Io and @hasDecl(std.Io, "sleep");
    std.debug.print("HAS_IO_SLEEP={}\n", .{has_sleep});
}
