// library_boundary_io_context_marker
// Category: hn_context
// HN marker: library_boundary_io
// Article marker: library_boundary
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=library_boundary_io_context_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=library_boundary_io\n", .{});
    std.debug.print("ARTICLE_MARKER=library_boundary\n", .{});
    std.debug.print("LIBRARY_BOUNDARY_IO=1\n", .{});
    if (@hasDecl(std, "Io")) {std.debug.print("HAS_IO=1\n", .{});}
}
