// local_compiler_truth_marker
// Category: safety_scope
// HN marker: safety_scope
// Article marker: local_compiler_only
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=local_compiler_truth_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=local_compiler_only\n", .{});
    std.debug.print("LOCAL_COMPILER_TRUTH_ONLY=1 ZIG_VERSION={}\n", .{@import("builtin").zig_version});
}
