// local_compiler_truth_marker
// Category: safety_scope
// Purpose: local compiler truth only
// HN marker: safety_scope
// Article marker: local_compiler_only
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: local_compiler_truth_marker
    // Purpose: local compiler truth only
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=local_compiler_truth_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=local_compiler_only\n", .{});
}
