// local_reasoning_limit_marker
// Category: hn_context
// HN marker: local_reasoning
// Article marker: local_reasoning
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=local_reasoning_limit_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=local_reasoning\n", .{});
    std.debug.print("ARTICLE_MARKER=local_reasoning\n", .{});
    std.debug.print("LOCAL_REASONING_LIMIT=1\n", .{});
}
