// local_reasoning_limit_marker
// Category: hn_context
// Purpose: local reasoning limit
// HN marker: local_reasoning
// Article marker: local_reasoning
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: local_reasoning_limit_marker
    // Purpose: local reasoning limit
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=local_reasoning_limit_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=local_reasoning\n", .{});
    std.debug.print("ARTICLE_MARKER=local_reasoning\n", .{});
}
