// no_external_payload_marker
// Category: safety_scope
// HN marker: safety_scope
// Article marker: no_external
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=no_external_payload_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_external\n", .{});
    std.debug.print("NO_EXTERNAL_PAYLOAD=1\n", .{});
}
