// no_global_async_safety_claim_marker
// Category: safety_scope
// HN marker: safety_scope
// Article marker: no_global_claim
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=no_global_async_safety_claim_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_global_claim\n", .{});
    std.debug.print("NO_GLOBAL_ASYNC_SAFETY_CLAIM=1\n", .{});
}
