// no_global_async_safety_claim_marker
// Category: safety_scope
// Purpose: no global safety claim
// HN marker: safety_scope
// Article marker: no_global_claim
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: no_global_async_safety_claim_marker
    // Purpose: no global safety claim
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=no_global_async_safety_claim_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_global_claim\n", .{});
}
