// no_network_io_marker
// Category: safety_scope
// Purpose: no network IO in lab
// HN marker: safety_scope
// Article marker: no_network
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: no_network_io_marker
    // Purpose: no network IO in lab
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=no_network_io_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_network\n", .{});
}
