// no_package_manager_marker
// Category: safety_scope
// Purpose: no package manager
// HN marker: safety_scope
// Article marker: no_pkg_mgr
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: no_package_manager_marker
    // Purpose: no package manager
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=no_package_manager_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_pkg_mgr\n", .{});
}
