// no_tls_marker
// Category: safety_scope
// Purpose: no TLS in lab
// HN marker: safety_scope
// Article marker: no_tls
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: no_tls_marker
    // Purpose: no TLS in lab
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=no_tls_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=no_tls\n", .{});
}
