// pre_1_0_api_changed_marker
// Category: version_probe
// HN marker: pre_1_0_api_changed
// Article marker: version_sensitive
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=pre_1_0_api_changed_marker\n", .{});
    std.debug.print("CATEGORY=version_probe\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=version_sensitive\n", .{});
    std.debug.print("PRE_1_0_API_CHANGED=1 ZIG_VERSION={}\n", .{@import("builtin").zig_version});
    std.debug.print("HAS_IO={}\n", .{@hasDecl(std, "Io")});
}
