// production_concurrency_verifier_not_tested_marker
// Category: safety_scope
// HN marker: safety_scope
// Article marker: not_production_verifier
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=production_concurrency_verifier_not_tested_marker\n", .{});
    std.debug.print("CATEGORY=safety_scope\n", .{});
    std.debug.print("HN_MARKER=safety_scope\n", .{});
    std.debug.print("ARTICLE_MARKER=not_production_verifier\n", .{});
    std.debug.print("NOT_A_PRODUCTION_CONCURRENCY_VERIFIER=1\n", .{});
}
