// single_threaded_deadlock_context_marker
// Category: deadlock
// HN marker: deadlock_concurrency_unavailable
// Article marker: deadlock
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=single_threaded_deadlock_context_marker\n", .{});
    std.debug.print("CATEGORY=deadlock\n", .{});
    std.debug.print("HN_MARKER=deadlock_concurrency_unavailable\n", .{});
    std.debug.print("ARTICLE_MARKER=deadlock\n", .{});
    std.debug.print("SINGLE_THREADED_DEADLOCK_CONTEXT=not_run_safe\n", .{});
    std.debug.print("DEADLOCK_GUARD=timeout_required\n", .{});
    
}
