// single_threaded_deadlock_context_marker
// Category: deadlock
// Purpose: single-threaded deadlock context
// HN marker: deadlock_concurrency_unavailable
// Article marker: deadlock
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: single_threaded_deadlock_context_marker
    // Purpose: single-threaded deadlock context
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=single_threaded_deadlock_context_marker\n", .{});
    std.debug.print("CATEGORY=deadlock\n", .{});
    std.debug.print("HN_MARKER=deadlock_concurrency_unavailable\n", .{});
    std.debug.print("ARTICLE_MARKER=deadlock\n", .{});
}
