// standard_library_abstraction_context_marker
// Category: hn_context
// HN marker: standard_library_abstraction
// Article marker: stdlib_abstraction
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=standard_library_abstraction_context_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=stdlib_abstraction\n", .{});
    std.debug.print("STDLIB_ABSTRACTION_CONTEXT=1\n", .{});
    std.debug.print("HAS_IO={}\n", .{@hasDecl(std, "Io")});
}
