// standard_library_abstraction_context_marker
// Category: hn_context
// Purpose: stdlib abstraction level debate
// HN marker: standard_library_abstraction
// Article marker: stdlib_abstraction
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: standard_library_abstraction_context_marker
    // Purpose: stdlib abstraction level debate
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=standard_library_abstraction_context_marker\n", .{});
    std.debug.print("CATEGORY=hn_context\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=stdlib_abstraction\n", .{});
}
