// std_io_type_shape_marker
// Category: stdlib_probe
// Purpose: probe Io type shape
// HN marker: library_boundary_io
// Article marker: std_io_design
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: std_io_type_shape_marker
    // Purpose: probe Io type shape
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=std_io_type_shape_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=library_boundary_io\n", .{});
    std.debug.print("ARTICLE_MARKER=std_io_design\n", .{});
}
