// std_io_threaded_exists_marker
// Category: stdlib_probe
// Purpose: check std.Io.Threaded exists
// HN marker: standard_library_abstraction
// Article marker: std_io_threaded
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: std_io_threaded_exists_marker
    // Purpose: check std.Io.Threaded exists
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=std_io_threaded_exists_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=std_io_threaded\n", .{});
}
