// std_io_threaded_exists_marker
// Category: stdlib_probe
// HN marker: standard_library_abstraction
// Article marker: std_io_threaded
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=std_io_threaded_exists_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=std_io_threaded\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_threaded = has_Io and @hasDecl(std.Io, "Threaded");
    std.debug.print("HAS_IO_THREADED={}\n", .{has_threaded});
    if (has_Io and !has_threaded) @compileError("std.Io.Threaded not found");
}
