// std_io_type_shape_marker
// Category: stdlib_probe
// HN marker: library_boundary_io
// Article marker: std_io_design
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=std_io_type_shape_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=library_boundary_io\n", .{});
    std.debug.print("ARTICLE_MARKER=std_io_design\n", .{});
    const has_Io = @hasDecl(std, "Io");
    std.debug.print("HAS_IO={}\n", .{has_Io});
    if (has_Io) {
        const Io = std.Io;
        std.debug.print("IO_TYPE={}\n", .{@typeName(Io)});
    }
}
