// std_io_namespace_probe_marker
// Category: stdlib_probe
// HN marker: standard_library_abstraction
// Article marker: std_io_design
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=std_io_namespace_probe_marker\n", .{});
    std.debug.print("CATEGORY=stdlib_probe\n", .{});
    std.debug.print("HN_MARKER=standard_library_abstraction\n", .{});
    std.debug.print("ARTICLE_MARKER=std_io_design\n", .{});
    const has_Io = @hasDecl(std, "Io");
    std.debug.print("HAS_STD_IO={}\n", .{has_Io});
    if (!has_Io) @compileError("std.Io not found - API changed");
}
