// threaded_pool_context_marker
// Category: deadlock
// Purpose: threaded pool context
// HN marker: async_vs_concurrent
// Article marker: threaded_io
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: threaded_pool_context_marker
    // Purpose: threaded pool context
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=threaded_pool_context_marker\n", .{});
    std.debug.print("CATEGORY=deadlock\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=threaded_io\n", .{});
}
