// threaded_pool_context_marker
// Category: deadlock
// HN marker: async_vs_concurrent
// Article marker: threaded_io
// Generated by generate_cases.py - API probes using @hasDecl(std, "Io")
const std = @import("std");

pub fn main() !void {
    std.debug.print("CASE_ID=threaded_pool_context_marker\n", .{});
    std.debug.print("CATEGORY=deadlock\n", .{});
    std.debug.print("HN_MARKER=async_vs_concurrent\n", .{});
    std.debug.print("ARTICLE_MARKER=threaded_io\n", .{});
    const has_Io = @hasDecl(std, "Io");
    const has_threaded = has_Io and @hasDecl(std.Io, "Threaded");
    std.debug.print("THREADED_POOL_CONTEXT={}\n", .{has_threaded});
}
