// try_before_second_await_footgun_marker
// Category: await_cancel
// Purpose: try before second await footgun
// HN marker: cancellation_await_ordering
// Article marker: await_ordering
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: try_before_second_await_footgun_marker
    // Purpose: try before second await footgun
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=try_before_second_await_footgun_marker\n", .{});
    std.debug.print("CATEGORY=await_cancel\n", .{});
    std.debug.print("HN_MARKER=cancellation_await_ordering\n", .{});
    std.debug.print("ARTICLE_MARKER=await_ordering\n", .{});
}
