// zig_env_std_dir_marker
// Category: version_probe
// Purpose: zig env std dir probe
// HN marker: pre_1_0_api_changed
// Article marker: version_sensitive
// Generated by generate_cases.py - deterministic
const std = @import("std");

pub fn main() !void {
    // Marker case: zig_env_std_dir_marker
    // Purpose: zig env std dir probe
    // This is a minimal probe stub. Real API validation depends on local Zig version.
    std.debug.print("CASE_ID=zig_env_std_dir_marker\n", .{});
    std.debug.print("CATEGORY=version_probe\n", .{});
    std.debug.print("HN_MARKER=pre_1_0_api_changed\n", .{});
    std.debug.print("ARTICLE_MARKER=version_sensitive\n", .{});
}
